Repository pyouroboros/ouroboros, pull requests merged in 2019-01, with the labels that each got.

#116 add changelog formatting and fix all labels going back to 1
  CHANGELOG.md
  doc/CHANGELOG.md
Labels: documentation

#119 fixed logic for latest vs develop, and added -f to specify file
  deploy.sh
Labels: bug

#126 fix readme wording for monitoring remote hosts
  README.md
Labels: documentation

#133 Allow stop-signal label
  pyouroboros/dockerclient.py
Labels: enhancement

#134 Clean old legacy files
  .dockerignore
  .flake8
  .travis.yml
  dev-environment.yml
  environment.yml
  requirements-dev.txt
  setup.py
Labels: cleanup

#151 Refactor/notifications with apprise
  README.md
  pyouroboros/__init__.py
  pyouroboros/config.py
  pyouroboros/dockerclient.py
  pyouroboros/helpers.py
  pyouroboros/notifiers.py
  pyouroboros/ouroboros.py
  requirements.txt
  setup.py
Labels: breaking change, cleanup, documentation, enhancement

#164 Recheck properly for only non lists
  pyouroboros/dataexporters.py
Labels: bug

#169 Patch/group 4
  pyouroboros/config.py
  pyouroboros/dockerclient.py
  pyouroboros/helpers.py
  pyouroboros/ouroboros.py
Labels: bug, cleanup
