Repository pyouroboros/ouroboros, pull requests merged in 2019-02, with the labels that each got.

#174 Flake8
  pyouroboros/dataexporters.py
  pyouroboros/dockerclient.py
Labels: duplicate

#175 v1.1.1 Merge
  pyouroboros/dataexporters.py
  pyouroboros/dockerclient.py
Labels: duplicate

#191 Monitor Ignored Re-Address + jenkins cleanup
  Dockerfile.arm
  Dockerfile.arm64
  README.md
  pyouroboros/dockerclient.py
Labels: bug, cleanup

#202 Add Warning for label_enable not set while using labels_only
  pyouroboros/config.py
Labels: enhancement

#218 Optimise dockerfile layers
  Dockerfile
  Dockerfile.arm
  Dockerfile.arm64
  setup.py
Labels: enhancement
